### ISSUE TITLE
Pgrouting выдает ошибку при установке в QGIS.

### ISSUE THREAD

**Issue by Sok46** [pgRouting/pgrouting#2270]
Pgrouting throws an error when installing in QGIS.

Pgrouting throws an error when installing in QGIS.PgAdmin with Postgis and Pgrouting works fine, the database successfully integrated into QGIS.

I searched many forums with this error, but none of the solutions helped.
![image](https://user-images.githubusercontent.com/103825098/163672191-0f54f870-3bf7-4b97-af34-c54e5a301976.png)

Failed to load module 'pgRoutingLayer' due to an error calling the initGui() method

pgRoutingLayer.connectors.postgis.DbError: 
Traceback (most recent call last):
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 162, in __init__
    self.con = psycopg2.connect(self.connection_info(), connect_timeout=5)
  File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: definition of service "NULL" not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python\qgis\utils.py", line 448, in startPlugin
    plugins[packageName].initGui()
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 240, in initGui
    self.reloadConnections()
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\pgRoutingLayer.py", line 272, in reloadConnections
    db = self.actionsDb[dbname].connect()
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\dbConnection.py", line 152, in connect
    conn = ConnectionManager.getConnection(self.type).connect(selected, self.parent())
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 149, in connect
    return Connection(uri)
  File "C:\Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pgRoutingLayer\connectors\postgis.py", line 164, in __init__
    raise DbError(e)
pgRoutingLayer.connectors.postgis.DbError: 

Версия Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Версия QGIS: 3.22.5-Białowieża Białowieża, c2723178 

Расположение Python:
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python
C:/Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.5\bin\python39.zip
C:\PROGRA~1\QGIS32~1.5\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib
C:\Program Files\QGIS 3.22.5\bin
C:\Users\doshi\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\GDAL-3.4.1-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\Pythonwin
C:/Users/doshi/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by Sok46** [comment]
Problem solved, I just didn't add all needed extensions to pgAdmin 
![image](https://user-images.githubusercontent.com/103825098/163706297-4b8ea1ce-3d25-4d54-9c91-886be30427d0.png)
